### ISSUE TITLE
How to run detr with only single class?

### ISSUE THREAD

**Issue by debparth** [facebookresearch/detr#156]
I'm trying to run detr on an image whilst having single class, but it always run into an error? Is it because I need to train on my dataset (I don't want to train it on any dataset cause I think that the models works fine for what I want and easily detects what I want to detect). Any Idea how to run it for detecting only single class?

**Comment by lessw2020** [comment]
Hi @debparth  - it's not a problem to train DETR on a single class.  (I have done many single class models with DETR).
You say you 'always hit an error' but what is the error?
For reference, you want to set num_classes =1...internally DETR will change that to 2 b/c it's your class + no object class.  
Make sure that the category id for the single class in your Coco json is 0. 
Also I'm not clear - you don't want to train your dataset but you think DETR will be able to work anyway?  
Is this class you want to detect one of the COCO classes already?  If so then you could just run the prebuilt DETR and restrict your results to the class you want in the prediction process.

**Comment by debparth** [comment]
Thank you for replying, contributor. 
Actually, I think that I need to detect "Person" class which is already in coco dataset and I don't think to train DETR on coco dataset of person class cause it's already their and also it detects fine so, I'm not thinking to train it. ( Still want your review that should I train it on person class or not? Will it make DETR model to detect better after training)
And I did set num_classes when I'm downloading the model. I already set num_classes = 1 `model = torch.hub.load('facebookresearch/detr', 'detr_resnet50', pretrained=True, num_classes = 1)` but still not getting it.
The error I get when I try to change the object detect classes to only one class i.e. "person" `CLASSES = [ 'person']`
I ran into this error: 
![Screenshot (5)](https://user-images.githubusercontent.com/53347017/88135869-e5440b80-cb9c-11ea-8a9a-4457a77d8137.png)

Could please tell me how to restrict the result of the class in the prediction process too?

**Comment by alcinos** [comment]
Hi @debparth 

Thank you for your interest in DETR.
It is totally possible to use DETR without retraining for a single class like "person", which is very common in COCO. Note however that if you are expecting to detect a lot of people in each image, it might be better to finetune the model on your dataset. See #9 for tips on how to do that.

If you simply want to run inference without retraining, you should NOT change the number of classes when you are loading the model from hub. Instead, you should load it as usual, run the inference as described in our Colab, then ignore (filter out) the predictions that have a class label different than the one you're interested in. The "person" class in COCO has label 1, so you can remove any prediction which doesn't have class 1.

Best of luck.

**Comment by debparth** [comment]
So, your saying that I need to create my dataset where there are a lot of peoples in single image and thus feed it to DETR. (Am I right!?)


After removing num_classes from the model line and changing this
`def plot_results(pil_img, prob, boxes):
    plt.figure(figsize=(16,10))
    plt.imshow(pil_img)
    ax = plt.gca()
    colors = COLORS * 100
    for p, (xmin, ymin, xmax, ymax), c in zip(prob, boxes.tolist(), colors):
        
        cl = p.argmax()
        text = f'{CLASSES[cl]}: {p[cl]:0.2f}'
        if text.split(":")[0] == 'person':
          ax.add_patch(plt.Rectangle((xmin, ymin), xmax - xmin, ymax - ymin,
                                   fill=False, color=c, linewidth=3))
          ax.text(xmin, ymin, text, fontsize=6,
                bbox=dict(facecolor='yellow', alpha=0.5))
    plt.axis('off')
    plt.show()`

and now I've got the below output:
<img width="907" alt="download (7)" src="https://user-images.githubusercontent.com/53347017/88360508-c83d4300-cd2a-11ea-86d2-e3cf6aee36ed.png">

Can you please tell me how can I make it better like to detect most of the person in the image?

**Comment by fmassa** [comment]
@debparth Hi,

Note that DETR currently struggles detecting small objects, so it might not see or be able to accurately localize many of the small instances in your image.

If you increase the image size that is feed to DETR, it will be able to detect more instances of the people in the image.

**Comment by debparth** [comment]
@fmassa  Thank you for your response. I resize the image and it work a bit. Did you try to load a video in DETR!? If you did then can share that code!?

**Comment by m3at** [comment]
@debparth if you're simply wondering how to repeat your detection over every frame in a video, then save the result as a video, I suggest using [imageio (see example)](https://imageio.readthedocs.io/en/stable/examples.html#convert-a-movie), it's a neat library.

If you're asking how to do the detection itself over time (a video), it's a bit out of scope for a github issue but to give you some pointers:
- Without changing the model, you could simply use the IoU of boxes on successive frames, and maybe refine that with Kalman filters. For example, take a look at: https://github.com/bochinski/iou-tracker
- By changing the model, taking multiple frame as input and using attention over time could be a fruitful approach. It's an open area of research 🙂

**Comment by yustiks** [comment]
> Hi @debparth - it's not a problem to train DETR on a single class. (I have done many single class models with DETR).
> You say you 'always hit an error' but what is the error?
> For reference, you want to set num_classes =1...internally DETR will change that to 2 b/c it's your class + no object class.
> Make sure that the category id for the single class in your Coco json is 0.
> Also I'm not clear - you don't want to train your dataset but you think DETR will be able to work anyway?
> Is this class you want to detect one of the COCO classes already? If so then you could just run the prebuilt DETR and restrict your results to the class you want in the prediction process.

Where should I set this parameter?

**Comment by lessw2020** [comment]
Hi @yustiks  - you can control the num_classes directly in:
https://github.com/facebookresearch/detr/blob/master/models/detr.py

by intercepting it right before the DETR model is made inside the build function.
(Better is to setup a pass through from args, but if you just want to get training and/or always have the same amount of classes this gets your running asap).
![detr_num_classes](https://user-images.githubusercontent.com/46302957/108547172-00940800-729f-11eb-9ff6-5f573dfdf9b3.JPG)

**Comment by yustiks** [comment]
> Hi @yustiks - you can control the num_classes directly in:
> https://github.com/facebookresearch/detr/blob/master/models/detr.py
> 
> by intercepting it right before the DETR model is made inside the build function.
> (Better is to setup a pass through from args, but if you just want to get training and/or always have the same amount of classes this gets your running asap).
> ![detr_num_classes](https://user-images.githubusercontent.com/46302957/108547172-00940800-729f-11eb-9ff6-5f573dfdf9b3.JPG)

Thank you!
This is very helpful!
Another question is related to the evaluation.
After 1 epoch of training, the script is crashed due to some error.
```
  File "main.py", line 248, in <module>
    main(args)
  File "main.py", line 215, in main
    model, criterion, postprocessors, data_loader_val, base_ds, device, args.output_dir
  File "/home/iivanova/miniconda3/envs/tf_gpu/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/iivanova/detr/engine.py", line 77, in evaluate
    coco_evaluator = CocoEvaluator(base_ds, iou_types)
  File "/home/iivanova/detr/datasets/coco_eval.py", line 31, in __init__
    self.coco_eval[iou_type] = COCOeval(coco_gt, iouType=iou_type)
  File "/home/iivanova/miniconda3/envs/tf_gpu/lib/python3.7/site-packages/pycocotools/cocoeval.py", line 81, in __init__
    self.params.catIds = sorted(cocoGt.getCatIds())
  File "/home/iivanova/miniconda3/envs/tf_gpu/lib/python3.7/site-packages/pycocotools/coco.py", line 170, in getCatIds
    cats = self.dataset['categories']
KeyError: 'categories'
```

Any idea what is it?

**Comment by yustiks** [comment]
Ok, I have found that in the custom coco-like dataset I didn't have categories key in annotations.. 
I have another question related to where the weights are stored in after training?

**Comment by lessw2020** [comment]
Hi @yustiks  - 
the weights are saved as 'checkpoint_epochnumber.pth' and a single 'checkpoint.pth' under the output directory.  

I run a completely custom setup but if you are running with the default main.py then saving is controlled by the:
--output_dir 
param in the args.  
Note that default is '', which means it won't save anything.  Thus you'll need to give it a dir to use if you want to save your weights, or adjust the code in main.py.
Hope that helps!

**Comment by yustiks** [comment]
> Hi @yustiks -
> the weights are saved as 'checkpoint_epochnumber.pth' and a single 'checkpoint.pth' under the output directory.
> 
> I run a completely custom setup but if you are running with the default main.py then saving is controlled by the:
> --output_dir
> param in the args.
> Note that default is '', which means it won't save anything. Thus you'll need to give it a dir to use if you want to save your weights, or adjust the code in main.py.
> Hope that helps!

Thank you! It helped me, yes!
Another question is related towards evaluation.
After training the network for 144 epochs, I still have 0 MaP.
```
Accumulating evaluation results...
DONE (t=0.02s).
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
```

what could be the problem?

**Comment by lessw2020** [comment]
Hi @yustiks  - 
for something like this (0.000 results) I would first look closely at your underlying dataset.  
Most likely the labelling or classes are mixed up meaning DETR can't possibly learn it. 
Also, are you using the built in DETR plot utility?  You can monitor it during training as no need to waste 144 epochs if it's not going well after the first 5 - 10 epochs.
I posted a dataset verifier utility a while back - you could run that on your dataset to start and ensure some basic things are correct. Let me go find the link for it.

**Comment by lessw2020** [comment]
Tthis util will compress your coco dataset to ensure no 'holes' in the class labelling, and then rebase it to 0:
![thunder_compress_view 1](https://user-images.githubusercontent.com/46302957/108639444-61f7da80-7449-11eb-87df-653294c5c8e4.PNG)
https://github.com/lessw2020/Thunder-Detr/blob/master/td_utils/thunder_file_utils.py

Beyond that are you sure that you have setup the head properly from the pre-trained DETR version?

**Comment by yustiks** [comment]
> Tthis util will compress your coco dataset to ensure no 'holes' in the class labelling, and then rebase it to 0:
> ![thunder_compress_view 1](https://user-images.githubusercontent.com/46302957/108639444-61f7da80-7449-11eb-87df-653294c5c8e4.PNG)
> https://github.com/lessw2020/Thunder-Detr/blob/master/td_utils/thunder_file_utils.py
> 
> Beyond that are you sure that you have setup the head properly from the pre-trained DETR version?

Thank you for reply. 
I checked the categories, they are written as following:
`[{'supercategory': 'object', 'id': 0, 'name': 'digit'}]`

how to check the setup of the head?

**Comment by aleenarayamajhi** [comment]
Hi @alcinos @lessw2020 I'm running into an error when I run main.py. I'm trying to train for one class using coco datasets. The error looks like this:
`run F:/DETR/detr/main.py --dataset_file face --data_path F:/DETR/dataset/ --output_dir F:/DETR/output --resume F:/DETR/weights/detr-r50-e632da11.pth`
```
Not using distributed mode
git:
  sha: 3c5317060f0c2ee3d1dccd3c4da23b3c2cb251bf, status: has uncommited changes, branch: master

Namespace(aux_loss=True, backbone='resnet50', batch_size=2, bbox_loss_coef=5, clip_max_norm=0.1, coco_panoptic_path=None, data_path='F:/DETR/dataset/', dataset_file='face', dec_layers=6, device='cuda', dice_loss_coef=1, dilation=False, dim_feedforward=2048, dist_url='env://', distributed=False, dropout=0.1, enc_layers=6, eos_coef=0.1, epochs=300, eval=False, frozen_weights=None, giou_loss_coef=2, hidden_dim=256, lr=0.0001, lr_backbone=1e-05, lr_drop=200, mask_loss_coef=1, masks=False, nheads=8, num_queries=30, num_workers=2, output_dir='F:/DETR/output', position_embedding='sine', pre_norm=False, remove_difficult=False, resume='F:/DETR/weights/detr-r50-e632da11.pth', seed=42, set_cost_bbox=5, set_cost_class=1, set_cost_giou=2, start_epoch=0, weight_decay=0.0001, world_size=1)
number of params: 41261318
IMAGE FOLDER:  F:\DETR\dataset\train
ANN_FILE:  F:\DETR\dataset\train.json
loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
IMAGE FOLDER:  F:\DETR\dataset\val
ANN_FILE:  F:\DETR\dataset\val.json
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
Length of Dataset train:  500
Length of Dataset val:  100
Start training
Epoch: [0]  [  0/250]  eta: 0:11:30  lr: 0.000100  class_error: 2.00  loss: 36.0587 (36.0587)  loss_ce: 0.3236 (0.3236)  loss_bbox: 4.4387 (4.4387)  loss_giou: 1.5512 (1.5512)  loss_ce_0: 0.2778 (0.2778)  loss_bbox_0: 3.5100 (3.5100)  loss_giou_0: 1.8308 (1.8308)  loss_ce_1: 0.2402 (0.2402)  loss_bbox_1: 3.9349 (3.9349)  loss_giou_1: 1.7132 (1.7132)  loss_ce_2: 0.2037 (0.2037)  loss_bbox_2: 4.0667 (4.0667)  loss_giou_2: 1.6071 (1.6071)  loss_ce_3: 0.2174 (0.2174)  loss_bbox_3: 4.4361 (4.4361)  loss_giou_3: 1.5737 (1.5737)  loss_ce_4: 0.2624 (0.2624)  loss_bbox_4: 4.3035 (4.3035)  loss_giou_4: 1.5675 (1.5675)  loss_ce_unscaled: 0.3236 (0.3236)  class_error_unscaled: 2.0000 (2.0000)  loss_bbox_unscaled: 0.8877 (0.8877)  loss_giou_unscaled: 0.7756 (0.7756)  cardinality_error_unscaled: 33.5000 (33.5000)  loss_ce_0_unscaled: 0.2778 (0.2778)  loss_bbox_0_unscaled: 0.7020 (0.7020)  loss_giou_0_unscaled: 0.9154 (0.9154)  cardinality_error_0_unscaled: 34.0000 (34.0000)  loss_ce_1_unscaled: 0.2402 (0.2402)  loss_bbox_1_unscaled: 0.7870 (0.7870)  loss_giou_1_unscaled: 0.8566 (0.8566)  cardinality_error_1_unscaled: 34.0000 (34.0000)  loss_ce_2_unscaled: 0.2037 (0.2037)  loss_bbox_2_unscaled: 0.8133 (0.8133)  loss_giou_2_unscaled: 0.8036 (0.8036)  cardinality_error_2_unscaled: 34.0000 (34.0000)  loss_ce_3_unscaled: 0.2174 (0.2174)  loss_bbox_3_unscaled: 0.8872 (0.8872)  loss_giou_3_unscaled: 0.7869 (0.7869)  cardinality_error_3_unscaled: 34.0000 (34.0000)  loss_ce_4_unscaled: 0.2624 (0.2624)  loss_bbox_4_unscaled: 0.8607 (0.8607)  loss_giou_4_unscaled: 0.7838 (0.7838)  cardinality_error_4_unscaled: 34.0000 (34.0000)  time: 2.7605  data: 2.1511  max mem: 3155
Traceback (most recent call last):

  File "F:\DETR\detr\main.py", line 259, in <module>
    main(args)

  File "F:\DETR\detr\main.py", line 209, in main
    args.clip_max_norm)

  File "F:\DETR\detr\engine.py", line 33, in train_one_epoch
    loss_dict = criterion(outputs, targets)

  File "C:\ProgramData\Anaconda3\envs\demo\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)

  File "F:\DETR\detr\models\detr.py", line 224, in forward
    indices = self.matcher(outputs_without_aux, targets)

  File "C:\ProgramData\Anaconda3\envs\demo\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)

  File "C:\ProgramData\Anaconda3\envs\demo\lib\site-packages\torch\autograd\grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)

  File "F:\DETR\detr\models\matcher.py", line 74, in forward
    cost_giou = -generalized_box_iou(box_cxcywh_to_xyxy(out_bbox), box_cxcywh_to_xyxy(tgt_bbox))

  File "F:\DETR\detr\util\box_ops.py", line 51, in generalized_box_iou
    assert (boxes1[:, 2:] >= boxes1[:, :2]).all()

AssertionError
```
