### ISSUE TITLE
How to train on custom datasets? Index out of bounds error

### ISSUE THREAD

**Issue by tenshis** [facebookresearch/detr#190]
I trained DETR successfully on the balloon images dataset. This came with VIA annotations which I could transform to COCO. But as soon as I try another dataset with converted VOC annotations (also to COCO), I receive the following error:

```
Traceback (most recent call last):

  File "main.py", line 251, in <module>
    main(args)

  File "main.py", line 201, in main
    args.clip_max_norm)

  File "/content/detr/engine.py", line 36, in train_one_epoch
    loss_dict = criterion(outputs, targets)

  File "/home/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)

  File "/content/detr/models/detr.py", line 225, in forward
    indices = self.matcher(outputs_without_aux, targets)

  File "/home/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)

  File "/home/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)

  File "/content/detr/models/matcher.py", line 71, in forward
    cost_class = -out_prob[:, tgt_ids]

IndexError: index 3 is out of bounds for dimension 0 with size 3
```

I can't really see differences between the converted COCO annotations, except that the second dataset has no segmentations. Is that an issue?

**Comment by alcinos** [comment]
Hi,
This looks like you didn't set the correct number of classes

**Comment by tenshis** [comment]
You're right, it's working now. I saw there's a PR to add a num_classes argument, that would be a great addition.

**Comment by mytk2012** [comment]
hi,can you me suggestions about training on custom dataset except actions like changing num_class. Shall I need to change the coco_class name? I have checked in the project that there is no coco_class name.
