### ISSUE TITLE
torchscript libtorch c++

### ISSUE THREAD

**Issue by femust** [facebookresearch/detr#309]
## ❓ How to do something using DETR
Hey, so I would like to import detr_panoptic to libtorch c++, therefore I follow the tutorial: [pytorch_torchscript_model](https://pytorch.org/tutorials/advanced/cpp_export.html), and I follow your implementation of the panoptic.

1. Input is the img 376x1241 RGB
Code:
```
transform = T.Compose([
    T.ToTensor(),
    T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
torch.cuda.empty_cache()
device = torch.device("cuda")
model_name = "detr_resnet101_panoptic"
model, postprocessor = torch.hub.load('facebookresearch/detr', model_name, pretrained=True, return_postprocessor=True)#, num_classes=250)
model.eval();
model = model.to(device)
img = transform(cam2_image)
img = transform(cam2_image).unsqueeze(0).to(device)
traced_script_module = torch.jit.trace(model, img)
traced_script_module.save("detr_panoptic_101.pt")
```

I got the following error:

```
/home/andrzej/.local/lib/python3.6/site-packages/torch/tensor.py:467: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
/home/andrzej/.cache/torch/hub/facebookresearch_detr_master/models/segmentation.py:66: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return tensor.unsqueeze(1).repeat(1, int(length), 1, 1, 1).flatten(0, 1)
/home/andrzej/.cache/torch/hub/facebookresearch_detr_master/models/segmentation.py:113: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if cur_fpn.size(0) != x.size(0):
/home/andrzej/.cache/torch/hub/facebookresearch_detr_master/models/segmentation.py:121: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if cur_fpn.size(0) != x.size(0):
/home/andrzej/.cache/torch/hub/facebookresearch_detr_master/models/segmentation.py:129: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if cur_fpn.size(0) != x.size(0):
Traceback (most recent call last):
  File "/home/andrzej/code_workspace/deep_learning_lo/deep_lo/parsing_pytorch_to_cpp.py", line 67, in <module>
    traced_script_module = torch.jit.trace(model, img)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 875, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 1027, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
RuntimeError: Only tensors, lists and tuples of tensors can be output from traced functions

Process finished with exit code 1 

```

I am not sure what's that since the variable **img** is a type of torch.Tensor... so it should be fine?

**Comment by zhiqwang** [comment]
Hi @femust , I think that you can refer to the unittest as below:

https://github.com/facebookresearch/detr/blob/a54b77800eb8e64e3ad0d8237789fcbf2f8350c5/test_all.py#L105-L123

**Comment by zhiqwang** [comment]
> I am not sure what's that since the variable img is a type of torch.Tensor... so it should be fine?

`torch.jit.script` support dynamic batch inference, it works fine.

**Comment by femust** [comment]
Hmm ok, thanks for the clarification, but imo I got the following error, when I try to reproduce the code
```
/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py:152: UserWarning: 'q_proj_weight' was found in ScriptModule constants,  but it is a non-constant parameter. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py:152: UserWarning: 'k_proj_weight' was found in ScriptModule constants,  but it is a non-constant parameter. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py:152: UserWarning: 'v_proj_weight' was found in ScriptModule constants,  but it is a non-constant parameter. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py:152: UserWarning: 'in_proj_weight' was found in ScriptModule constants,  but it is a non-constant parameter. Consider removing it.
  " but it is a non-constant {}. Consider removing it.".format(name, hint))
Traceback (most recent call last):
  File "/home/andrzej/code_workspace/deep_learning_lo/detr/parsing_pytorch_to_cpp.py", line 28, in <module>
    scripted_model = torch.jit.script(wrapped_model)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 1261, in script
    return torch.jit._recursive.create_script_module(obj, torch.jit._recursive.infer_methods_to_compile)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 305, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 357, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 1606, in _construct
    init_fn(script_module)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 340, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, infer_methods_to_compile)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 357, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 1606, in _construct
    init_fn(script_module)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 340, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, infer_methods_to_compile)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 357, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 1606, in _construct
    init_fn(script_module)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 340, in init_fn
    scripted = create_script_module_impl(orig_value, sub_concrete_type, infer_methods_to_compile)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 361, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 279, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
RuntimeError: 
Unknown type name 'NestedTensor':
  File "/home/andrzej/code_workspace/deep_learning_lo/detr/models/backbone.py", line 72
    def forward(self, tensor_list: NestedTensor):
                                   ~~~~~~~~~~~~ <--- HERE
        xs = self.body(tensor_list.tensors)
        out: Dict[str, NestedTensor] = {}


Process finished with exit code 1

```

Also, I have noticed now that when I run "test_all.py" It also throws the error for very similar reason.
```
======================================================================
ERROR: test_backbone_script (__main__.Tester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_all.py", line 69, in test_backbone_script
    torch.jit.script(backbone)  # noqa
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/__init__.py", line 1261, in script
    return torch.jit._recursive.create_script_module(obj, torch.jit._recursive.infer_methods_to_compile)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 305, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 361, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/jit/_recursive.py", line 279, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
RuntimeError: 
Unknown type name 'NestedTensor':
  File "/home/andrzej/code_workspace/deep_learning_lo/detr/models/backbone.py", line 72
    def forward(self, tensor_list: NestedTensor):
                                   ~~~~~~~~~~~~ <--- HERE
        xs = self.body(tensor_list.tensors)
        out: Dict[str, NestedTensor] = {}
```
Maybe is it due to the PyTorch version?

```
import torch
print(torch.__version__)
1.5.0
```

**Comment by zhiqwang** [comment]
Yep, pytorch 1.6.0+ should works

**Comment by femust** [comment]
Ok so the last two questions:

1) Why is there 
```
x = [torch.rand(3, 200, 200), torch.rand(3, 200, 250)]
```
as far as I understood it should represent the input for the detr, is that right? But those two tensors have different shape...

2) So the one problem that left is that in cpp, it seems it demenads List[Tensor], but I provide only Tensor, but not sure whether there is a conversion somehow Tensor in List[Tensor] in cpp

So here is my code:

```
int main() {
  cv::Mat img = imread("path_to.png",   cv::IMREAD_COLOR);
  auto tensor = ToTensor(img);
  torch::jit::script::Module module;
  try {
    std::cout << "Loading model" << std::endl;
    // Deserialize the ScriptModule from a file using torch::jit::load().
    module = torch::jit::load(
        "/home/andrzej/code_workspace/more_tests/detr_resnet101_panoptic.pt");
    std::cout << "Model loaded" << std::endl;
  } catch (const torch::Error& e) {
    std::cout << "error loading the model" << std::endl;
    return -1;
  } catch (const std::exception& e) {
    std::cout << "Other error: " << e.what() << std::endl;
    return -1;
  }
  std::vector<torch::jit::IValue> inputs;
  inputs.push_back(tensor);
  // Execute the model and turn its output into a tensor.
  at::Tensor output = module.forward(inputs).toTensor();
  // std::cout << output.slice(/*dim=*/1, /*start=*/0, /*end=*/5) << '\n';
  return 0;
}
```
Function Opencv->Torch
```
auto ToTensor(cv::Mat img, bool show_output = false, bool unsqueeze=false, int unsqueeze_dim = 0)
{
    std::cout << "image shape: " << img.size() << std::endl;
    at::Tensor tensor_image = torch::from_blob(img.data, { 3, img.rows, img.cols  }, at::kByte);

    if (unsqueeze)
    {
        tensor_image.unsqueeze_(unsqueeze_dim);
        std::cout << "tensors new shape: " << tensor_image.sizes() << std::endl;
    }

    if (show_output)
    {
        std::cout << tensor_image.slice(2, 0, 1) << std::endl;
    }
    std::cout << "tenor shape: " << tensor_image.sizes() << std::endl;
    return tensor_image;
}
```
the output
```
image shape: [1241 x 376]
tenor shape: [3, 376, 1241]
Loading model
Model loaded
terminate called after throwing an instance of 'c10::Error'
  what():  forward() Expected a value of type 'List[Tensor]' for argument 'inputs' but instead found type 'Tensor'.
Position: 1
Declaration: forward(__torch__.WrappedDETR self, Tensor[] inputs) -> (Dict(str, Tensor))
Exception raised from checkArg at ../aten/src/ATen/core/function_schema_inl.h:193 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x7f2108ca2b89 in /home/andrzej/Libraries/libtorch/lib/libc10.so)
frame #1: <unknown function> + 0xbc231b (0x7f20f8adc31b in /home/andrzej/Libraries/libtorch/lib/libtorch_cpu.so)
frame #2: <unknown function> + 0xbc5a83 (0x7f20f8adfa83 in /home/andrzej/Libraries/libtorch/lib/libtorch_cpu.so)
frame #3: torch::jit::GraphFunction::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, c10::IValue> > > const&) + 0x2d (0x7f20facba63d in /home/andrzej/Libraries/libtorch/lib/libtorch_cpu.so)
frame #4: torch::jit::Method::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, c10::IValue> > > const&) + 0x16f (0x7f20faccb42f in /home/andrzej/Libraries/libtorch/lib/libtorch_cpu.so)
frame #5: torch::jit::Module::forward(std::vector<c10::IValue, std::allocator<c10::IValue> >) + 0xff (0x561fc614fe79 in ./more_tests)
frame #6: main + 0x298 (0x561fc614938e in ./more_tests)
frame #7: __libc_start_main + 0xe7 (0x7f209c99eb97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #8: _start + 0x2a (0x561fc614842a in ./more_tests)

Aborted (core dumped)

```
So for me it seems to be a problem that during the python conversion I put 
```
x = [torch.randn(3, 376, 1241),torch.randn(3, 376, 1241) ]
```
 and therefore it needs List[Tensor], I tried to also put a single value in the python script 
so only for example 
```
x = torch.randn(3, 376, 1241)
```
but then I got 
```
Traceback (most recent call last):
  File "/home/andrzej/code_workspace/deep_learning_lo/detr/parsing_pytorch_to_cpp.py", line 24, in <module>
    out = wrapped_model(dummy_input)
  File "/home/andrzej/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/andrzej/code_workspace/deep_learning_lo/detr/parsing_pytorch_to_cpp.py", line 14, in forward
    sample = nested_tensor_from_tensor_list(inputs)
  File "/home/andrzej/code_workspace/deep_learning_lo/detr/util/misc.py", line 327, in nested_tensor_from_tensor_list
    raise ValueError('not supported')
ValueError: not supported

Process finished with exit code 1
``` Which seems self-explanatory :) so if @zhiqwang  you know how to work around this I will appreciate.

**Comment by zhiqwang** [comment]
> Ok so the last two questions:
> 
> 1. Why is there
> 
> ```
> x = [torch.rand(3, 200, 200), torch.rand(3, 200, 250)]
> ```
> 
> as far as I understood it should represent the input for the detr, is that right? But those two tensors have different shape...

Yep, and libtorch support dynamic batch inferece in this ways, it's a little tricky.

> 1. So the one problem that left is that in cpp, it seems it demenads List[Tensor], but I provide only Tensor, but not sure whether there is a conversion somehow Tensor in List[Tensor] in cpp

I've added a libtorch inference scripts in my own branch [here](https://github.com/zhiqwang/detr/tree/deployment/deployment), maybe you can refer to the code. At my branch, the libtorch inference doesn't contain the `postprocessor` parts, and maybe it's convenient to add `postprocessor` to the `torchscript`.

**Comment by femust** [comment]
Okey, I managed to run it on cpp based on your branch and instructions,

Some thoughts:
1)
```
class WrappedDETR(nn.Module):
    def __init__(self, model):
        super().__init__()
        self.model = model
    def forward(self, inputs: List[Tensor]):
        sample = nested_tensor_from_tensor_list(inputs)
        return self.model(sample)
``` 
So in this case forward needs to be List[Tensor], because then in cpp we have:
```
  IValue forward(std::vector<IValue> inputs) {
    return get_method("forward")(std::move(inputs));
  }
```
Is that correct?
Couldn't be this done in a kind of overloading, so it would be more "logical" that I want to only evaluate one img (tensor), for example when I use it for a robot, where I evaluate one image at the time? 

2) Wouldn't be possible to do also preprocessing and postprocessing in the script ? So something like
```
class WrappedDETR(nn.Module):
    def __init__(self, model, postprocessor):
        super().__init__()
        self.model = model
        self.postprocessor = postprocessor
    def transform(self):
        self.transform = T.Compose([T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])
    def forward(self, inputs: List[Tensor]):
        #here throws an error
        for i in range(len(inputs)):
            inputs[i] = self.transform(inputs[i])
        sample = nested_tensor_from_tensor_list(inputs)
        out = self.model(sample)
        #here as well
        result = postprocessor(out, inputs[0].unsqueeze(0))[0]
        return result
if __name__ == "__main__":
    model, postprocessor = detr_resnet101_panoptic(pretrained=True, return_postprocessor=True)
    wrapped_model = WrappedDETR(model, postprocessor)
    wrapped_model.eval()
    scripted_model = torch.jit.script(wrapped_model)
    scripted_model.save("detr_resnet101_panoptic.torchscript.pt")
```
Here currently I have two errors due to looping over tensors, and not sure what exactly should be the output of the postprocessor step? Since the result has the categories like segments_info, png_string, but the png_string is encoded so then it may be problematic to decode this in OpenCV (in general to have overall real-time performance)

**Comment by zhiqwang** [comment]
1. A list containing only one element is also a list.
2. The docs seems a little outdated. I'll try how to add the `postprocessor` to the `litborch` model later. But `nested_tensor_from_tensor_list` play the role of pre-processing, if you want to subtract mean and divide std, you can just put this in the `OpenCV` function.

**Comment by ma-siddiqui** [comment]
Hi,

Same I am faced. so what is the final solution, it would be great if you can share the working code.

Thanks,

**Comment by ma-siddiqui** [comment]
The issue resolved when shifted to pytorch 1.6

**Comment by ananthu-aniraj** [comment]
Hi,
I managed to add the postprocessing to the scripted model. If anyone is interested, here is the code:
`
class WrappedDETR(nn.Module): 
    def __init__(self, model): 
        super().__init__()
        
        self.model = model

    def forward(self, inputs: List[Tensor], target_sizes: Tensor, confidence_threshold:float): 
        
            
        sample = nested_tensor_from_tensor_list(inputs)
        
        outputs = self.model(sample)
        
        out_logits, out_bbox = outputs['pred_logits'], outputs['pred_boxes']
        
        prob = F.softmax(out_logits, -1)
        scores, labels = prob[..., :-1].max(-1)

        # convert to [x0, y0, x1, y1] format
        boxes = box_ops.box_cxcywh_to_xyxy(out_bbox)
        # and from relative [0, 1] to absolute [0, height] coordinates
        img_h, img_w = target_sizes.unbind(1)
        scale_fct = torch.stack([img_w, img_h, img_w, img_h], dim=1)
        boxes = boxes * scale_fct[:, None, :]
        
        keep_batch = scores>=confidence_threshold
        
        results = [{'scores': s[k], 'pred_classes': l[k], 'pred_boxes': b[k]} for s, l, b, k in zip(scores, labels, boxes, keep_batch)]
        
        return results

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

model = torch.hub.load('facebookresearch/detr:main', 'detr_resnet50', pretrained=True)

# Copy model to GPU if available
model.to(device)

model.transformer = torch.jit.script(model.transformer)

wrapped_model = WrappedDETR(model)

wrapped_model.eval()
scripted_model = torch.jit.script(wrapped_model)
scripted_model.eval()
`

**Comment by ananthu-aniraj** [comment]
@Mona77 This is what worked for me with the segmentation model
`class WrappedDETR(nn.Module): 
    def __init__(self, model): 
        super().__init__()
        
        self.model = model
        
        
        


    def forward(self, inputs: List[Tensor], target_sizes: Tensor, confidence_threshold:float): 
        
            
        sample = nested_tensor_from_tensor_list(inputs)
        
        outputs = self.model(sample)
        
        out_logits, out_bbox, out_masks = outputs['pred_logits'], outputs['pred_boxes'], outputs['pred_masks']
        
        prob = F.softmax(out_logits, -1)
        scores, labels = prob[..., :-1].max(-1)

        # convert to [x0, y0, x1, y1] format
        boxes = box_ops.box_cxcywh_to_xyxy(out_bbox)
        # and from relative [0, 1] to absolute [0, height] coordinates
        img_h, img_w = target_sizes.unbind(1)
        scale_fct = torch.stack([img_w, img_h, img_w, img_h], dim=1)
        boxes = boxes * scale_fct[:, None, :]
        
        outputs_masks = F.interpolate(out_masks, size=[int(img_h[0].item()),int(img_w[0].item())], mode="bilinear", align_corners=False)
        outputs_masks = outputs_masks.sigmoid() > confidence_threshold
        
        keep_batch = scores>=confidence_threshold
        
        results = [{'scores': s[k], 'pred_classes': l[k], 'pred_boxes': b[k], 'pred_masks': m[k]} for s, l, b, k, m in zip(scores, labels, boxes, keep_batch, outputs_masks)]
        
        return results
    

if __name__ == '__main__':
    
    args = parse_args() 
    
    p = Path(args["save_path"])
    p.mkdir(parents=True,exist_ok=True)
    
    save_ext = ".pt"
    
    base_path_images_in = args["input_path_images"]
    image_names_in = glob.glob(base_path_images_in + "/**/*.jpg",recursive = True)
   
    # Load classnames
    class_names = read_txt_file(args["class_names"])    
    # Load model
    model,postprocessor = torch.hub.load('', 'detr_resnet50_instance_segm', 
                           source='local', pretrained=True, return_postprocessor=True, num_classes = len(class_names), checkpoint_path = args["input_path"])
    
    # Copy model to GPU if available
    model.to(device)
    
    model.detr.transformer = torch.jit.script(model.detr.transformer)
    
    wrapped_model = WrappedDETR(model)
    
    wrapped_model.eval()
    scripted_model = torch.jit.script(wrapped_model)
    scripted_model.eval()
    
    inputs = []
    im_sizes= []
    selected_im_batch = [image_names_in[0]]
    
    for item in selected_im_batch:
        batch_im_cv2 = cv2.cvtColor(cv2.imread(item), cv2.COLOR_BGR2RGB)
        batch_im = Image.fromarray(batch_im_cv2)
        im_sizes.append(torch.tensor(batch_im.size[::-1]))
        batch_img_tensor = transform(batch_im).to(device)
        inputs.append(batch_img_tensor) # inputs is ready
    
    im_sizes = torch.stack(im_sizes).to(device)
        
    
    confidence_threshold = 0.5
    out = wrapped_model(inputs,im_sizes,confidence_threshold)
    out_script = scripted_model(inputs,im_sizes,confidence_threshold)
    print(len(out_script))
    
    
    if out[0]["scores"].equal(out_script[0]["scores"]) and out[0]["pred_boxes"].equal(out_script[0]["pred_boxes"]):
        print("Scripting successful!, Saving to ", os.path.join(args["save_path"],args["model_name"]+save_ext))   
    
    
    if(args["system_specific_optimize"]):
        fnet = torch.jit.optimize_for_inference(torch.jit.freeze(scripted_model))
    else:
        fnet = torch.jit.freeze(scripted_model)

    fnet.save(os.path.join(args["save_path"],args["model_name"]+save_ext))`
