### ISSUE TITLE
unable to train model

### ISSUE THREAD

**Issue by ohjunee** [facebookresearch/detr#339]
## ❓ How to do something using DETR

Environment
pytorch 1.7.1
torchvision 0.8.2

I've trained the model with one node, 1 gpu, but I entered the command as follows, and an error occurred.

>> python -m torch.distributed.launch --nproc_per_node=1 --use_env main.py --coco_path /path/to/coco

| distributed init (rank 0): env://
Traceback (most recent call last):
  File "main.py", line 248, in <module>
    main(args)
  File "main.py", line 106, in main
    utils.init_distributed_mode(args)
  File "C:\Users\OHJUN\Desktop\연구자료\2021-1\석사2기\DETR\DETR\util\misc.py", line 426, in init_distributed_mode
    world_size=args.world_size, rank=args.rank)
  File "C:\Users\OHJUN\anaconda3\envs\detr_master\lib\site-packages\torch\distributed\distributed_c10d.py", line 434, in init_process_group
    init_method, rank, world_size, timeout=timeout
  File "C:\Users\OHJUN\anaconda3\envs\detr_master\lib\site-packages\torch\distributed\rendezvous.py", line 82, in rendezvous
    raise RuntimeError("No rendezvous handler for {}://".format(result.scheme))
RuntimeError: No rendezvous handler for env://
Traceback (most recent call last):
  File "C:\Users\OHJUN\anaconda3\envs\detr_master\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\OHJUN\anaconda3\envs\detr_master\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\OHJUN\anaconda3\envs\detr_master\lib\site-packages\torch\distributed\launch.py", line 260, in <module>
    main()
  File "C:\Users\OHJUN\anaconda3\envs\detr_master\lib\site-packages\torch\distributed\launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\OHJUN\\anaconda3\\envs\\detr_master\\python.exe', '-u', 'main.py', '--coco_path', '/path/to/coco']' returned non-zero exit status 1.

I'd appreciate it if someone could help me...

**Comment by lessw2020** [comment]
I'm a bit confused as to whether your issue is 
a)unable to start training (per the title) 
or 
b)unable to launch a trained model (per the first line in your issue).

But - the initial takeaway is if you are training for a single gpu, then the args.distributed needs to be False. 

From the error stack, it's trying to look for a rendevous handler which is not present since you are not in a distributed setup.

Most likely you have RANK or WORLD_SIZE set in your environ and it's prompting it to  attempt distributed  setup, as you should have already bounced out with args.distributed = False and not end up at line 426 as shown in the stack trace above.

You could either hardcode the distributed check (i.e. force args.distributed = False and comment out the call to init_distributed_mode)  or otherwise check your environ variables per these:
~~~
def init_distributed_mode(args):
    if 'RANK' in os.environ and 'WORLD_SIZE' in os.environ:
        args.rank = int(os.environ["RANK"])
        args.world_size = int(os.environ['WORLD_SIZE'])
        args.gpu = int(os.environ['LOCAL_RANK'])
    elif 'SLURM_PROCID' in os.environ:
        args.rank = int(os.environ['SLURM_PROCID'])
        args.gpu = args.rank % torch.cuda.device_count()
    else:
        print('Not using distributed mode')
        args.distributed = False
        return

**Comment by ohjunee** [comment]
The problem I'm asking is about a). 
I realized that distributed learning is not possible because it is a single gpu. 
I am training the model as follows, and I wonder if it is the same way as you said above.

>> python main.py --coco_path /path/to/coco

**Comment by ohjunee** [comment]
> I'm a bit confused as to whether your issue is
> a)unable to start training (per the title)
> or
> b)unable to launch a trained model (per the first line in your issue).
> 
> But - the initial takeaway is if you are training for a single gpu, then the args.distributed needs to be False.
> 
> From the error stack, it's trying to look for a rendevous handler which is not present since you are not in a distributed setup.
> 
> Most likely you have RANK or WORLD_SIZE set in your environ and it's prompting it to attempt distributed setup, as you should have already bounced out with args.distributed = False and not end up at line 426 as shown in the stack trace above.
> 
> You could either hardcode the distributed check (i.e. force args.distributed = False and comment out the call to init_distributed_mode) or otherwise check your environ variables per these:
> 
> ```
> def init_distributed_mode(args):
>     if 'RANK' in os.environ and 'WORLD_SIZE' in os.environ:
>         args.rank = int(os.environ["RANK"])
>         args.world_size = int(os.environ['WORLD_SIZE'])
>         args.gpu = int(os.environ['LOCAL_RANK'])
>     elif 'SLURM_PROCID' in os.environ:
>         args.rank = int(os.environ['SLURM_PROCID'])
>         args.gpu = args.rank % torch.cuda.device_count()
>     else:
>         print('Not using distributed mode')
>         args.distributed = False
>         return
> ```

The problem I'm asking is about a). 
I realized that distributed learning is not possible because it is a single gpu. 
I am training the model as follows, and I wonder if it is the same way as you said above.

>> python main.py --coco_path /path/to/coco

**Comment by Alberto1404** [comment]
Same doubt. torch.distributed.launch is used only with multi GPU. How to train with single GPU here? Just typing ```python main.py ...```?
