### ISSUE TITLE
How to calculate the modifed DETR model's flops

### ISSUE THREAD

**Issue by 1338199** [facebookresearch/detr#344]
Hi,
     I have done some modifications to DETR's architectures. And I want to calculate the modifed model's flops, but I found your calculation script provided in issue [110](https://github.com/facebookresearch/detr/issues/110) will report lots of assertion 
erros such as:
```
jit_handles.py", line 237, in matmul_flop_jit                             
    assert input_shapes[0][-1] == input_shapes[1][0]                                                                                                                                    
AssertionError
```
 If I ignore these assertion errors, then it will report :
```
m1_dim, m2_dim = input_shapes[1]                                                                                                                                                    
ValueError: too many values to unpack (expected 2) 
```
Does any other modifications I have to add to the origin calculation script? Thank you very much!

**Comment by alcinos** [comment]
From the look of it, it seems that there might be errors in the definition of your model. Please check that you can do inference both in normal and jitted mode, and retry with the script

Best of luck

**Comment by Blazer-007** [comment]
@alcinos  Can you suggest what are the changes required to be made in [these files](https://gist.github.com/fmassa/c0fbb9fe7bf53b533b5cc241f5c8234c) to find flops on a custom dataset? 

I have tried adding changing [this line](https://gist.github.com/fmassa/c0fbb9fe7bf53b533b5cc241f5c8234c#file-compute_flops-py-L62) to the following codes:-
```
model = torch.hub.load('facebookresearch/detr', model_name, pretrained = False, num_classes = 2)
checkpoint = torch.load('outputs/checkpoint.pth', map_location='cpu')
model.load_state_dict(checkpoint['model'], strict=False)
model.eval();
```

But got the following error:-
```
100% 97.8M/97.8M [00:00<00:00, 145MB/s]
  0% 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "compute_flops.py", line 73, in <module>
    res = flop_count(model, (inputs,))
  File "/content/drive/My Drive/detr/flop_count.py", line 169, in flop_count
    flops_counter = handle_count(inputs, outputs)
  File "/content/drive/My Drive/detr/jit_handles.py", line 158, in conv_flop_jit
    assert len(inputs) == 12
AssertionError
```

**Comment by wangyue7777** [comment]
> @alcinos Can you suggest what are the changes required to be made in [these files](https://gist.github.com/fmassa/c0fbb9fe7bf53b533b5cc241f5c8234c) to find flops on a custom dataset?
> 
> I have tried changing [this line](https://gist.github.com/fmassa/c0fbb9fe7bf53b533b5cc241f5c8234c#file-compute_flops-py-L62) to the following codes:-
> 
> ```
> model = torch.hub.load('facebookresearch/detr', model_name, pretrained = False, num_classes = 2)
> checkpoint = torch.load('outputs/checkpoint.pth', map_location='cpu')
> model.load_state_dict(checkpoint['model'], strict=False)
> model.eval();
> ```
> 
> But got the following error:-
> 
> ```
> 100% 97.8M/97.8M [00:00<00:00, 145MB/s]
>   0% 0/100 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "compute_flops.py", line 73, in <module>
>     res = flop_count(model, (inputs,))
>   File "/content/drive/My Drive/detr/flop_count.py", line 169, in flop_count
>     flops_counter = handle_count(inputs, outputs)
>   File "/content/drive/My Drive/detr/jit_handles.py", line 158, in conv_flop_jit
>     assert len(inputs) == 12
> AssertionError
> ```

Hi, I have the same problem as you!
Have you solve your problem yet?

**Comment by onepeachbiubiubiu** [comment]
> wangyue7777
This is caused by the torch version,  the jit output is incompatible when torch is upgraded. You can try torch 1.5 with torchvision 0.6.0.
