### ISSUE TITLE
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'

### ISSUE THREAD

**Issue by qwertykk** [facebookresearch/detr#346]
I am new to detr and trying to train a pre-trained model on a custom dataset.

I am using a university server with a single p100 GPU, python 3.9.1, torch 1.7.1. when I try to run the detr code from the command line using 
`python main.py --batch_size 2 --resume https://dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth --jrdb_path datasets/jrdb`  (jrdb_path is path to my dataset)
I get the following error

`Traceback (most recent call last):
  File "/mnt/lustre/projects/ih21/kmun0005/code/detr/main.py", line 252, in <module>
    main(args)
  File "/mnt/lustre/projects/ih21/kmun0005/code/detr/main.py", line 106, in main
    utils.init_distributed_mode(args)
  File "/mnt/lustre/projects/ih21/kmun0005/code/detr/util/misc.py", line 421, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/home/kmun0005/ih21/kmun0005/my_conda/conda/envs/detr/lib/python3.9/site-packages/torch/cuda/__init__.py", line 263, in set_device
    torch._C._cuda_setDevice(device)
AttributeError: module 'torch._C' has no attribute '_cuda_setDevice'
`

I am not really sure how to fix this. Please help

**Comment by DanielFennhagen** [comment]
Hi, this might help you:

https://github.com/pytorch/pytorch/issues/33655

**Comment by qwertykk** [comment]
> Hi, this might help you:
> 
> [pytorch/pytorch#33655](https://github.com/pytorch/pytorch/issues/33655)

I have already seen this link. didn't really help. the solution there is mostly focused on how to work around the problem in a CPU environment. it doesn't actually solve the problem.

**Comment by alcinos** [comment]
Could you double-check that you have a gpu-enabled pytorch version? Something like `t = torch.rand(35).cuda()` in interactive mode?

Otherwise I'd try to maybe upgrade pytorch, I'm not 100% sure that 1.7.1 supports python 3.9

Hope this helps.

**Comment by qwertykk** [comment]
I am sure i have a gpu-enabled pytorch version. I can run detr inference using cuda.

**Comment by arefm** [comment]
Hey @qwertykk, did you find any solution for it?

**Comment by mmabceric** [comment]
Try to install pytorch 1.6.0 with cuda 10.1.

I fixed my error by doing so. It seems that later versions of pytorch does not enable GPU while the code requires GPU.

**Comment by JunKaiLiao** [comment]
I have the same problem. Did any one solve it ?

**Comment by moured** [comment]
@augustleoo the solution you proposed worked for me. @JunKaiLiao just go here https://pytorch.org/get-started/previous-versions/ and try with different CUDA builds.
