### ISSUE TITLE
Index Error while training for instance segmentation on a trained box model.

### ISSUE THREAD

**Issue by Vaibhav-ML** [facebookresearch/detr#398]
Hi,

I tried to train an instance segmentation on a dataset which I have already trained on for bounding box detection.

I have used the checkpoint of that model for training instance segmentation as mentioned in the documentation

However I run into the below issue :

**: Caught IndexError in DataLoader worker process 0.**
Original Traceback (most recent call last):
  File "/sw/installed/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/sw/installed/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/sw/installed/PyTorch/1.6.0-fosscuda-2019b-Python-3.7.4/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/projects/p086/p_attention/detr/datasets/coco.py", line 27, in __getitem__
    img, target = self.prepare(img, target)
  File "/projects/p086/p_attention/detr/datasets/coco.py", line 76, in __call__
    masks = convert_coco_poly_to_mask(segmentations, h, w)
  File "/projects/p086/p_attention/detr/datasets/coco.py", line 36, in convert_coco_poly_to_mask
    rles = coco_mask.frPyObjects(polygons, height, width)
  File "pycocotools/_mask.pyx", line 292, in pycocotools._mask.frPyObjects
IndexError: list index out of range

How do I run instance segmentation? Please help.

**Comment by alcinos** [comment]
Hello,

Please check that your masks are correctly encoded, it seems that he cocoTools are not able to open them.

Best of luck

**Comment by Vaibhav-ML** [comment]
Hi,

I have not encoded any masks. my json file just containsn normal bounding box data.No polygons or polylines.

Can I do segmentation using this normal bbox json? Or do I need to relabel my data with polylines?

Regards,
Vaibhav Sharma

**Comment by alcinos** [comment]
For segmentation, you need segmentation masks.
It is completely useless to use boxes to do segmentation. The model is not going to learn anything it isn't already doing by predicting boxes.
To create correct coco annotations, you can try to mimick the COCO annotations or follow a guide like https://www.immersivelimit.com/tutorials/create-coco-annotations-from-scratch/#coco-dataset-format

**Comment by Vaibhav-ML** [comment]
Thanks a lot for the clarification. Will try this.

Regards
Vaibhav Sharma
