### ISSUE TITLE
COCO Metrics Evaluation on Custom Dataset

### ISSUE THREAD

**Issue by NyanSwanAung** [facebookresearch/detr#399]
## COCO Metrics Evaluation on Custom Dataset

I'm having this error when I tried to evaluate my trained model on my custom dataset. 
```bash
Building a DETR model with 2 classes
Traceback (most recent call last):
  File "detr/main.py", line 271, in <module>
    main(args)
  File "detr/main.py", line 137, in main
    model, criterion, postprocessors = build_model(args)
  File "/content/Object-Detection-Using-DETR-CustomDataset/detr/models/__init__.py", line 6, in build_model
    return build(args)
  File "/content/Object-Detection-Using-DETR-CustomDataset/detr/models/detr.py", line 335, in build
    aux_loss=args.aux_loss,
  File "/content/Object-Detection-Using-DETR-CustomDataset/detr/models/detr.py", line 39, in __init__
    self.query_embed = nn.Embedding(num_queries, hidden_dim)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/sparse.py", line 139, in __init__
    self.weight = Parameter(torch.empty((num_embeddings, embedding_dim), **factory_kwargs))
TypeError: empty() received an invalid combination of arguments - got (tuple, dtype=NoneType, device=NoneType), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.memory_format memory_format, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.memory_format memory_format, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)* 
 ```

I used the same evaluation code as mentioned in readme which is 
```python
python main.py --batch_size 2 --no_aux_loss --eval \
    --resume https://dl.fbaipublicfiles.com/detr/detr-r50-e632da11.pth \
    --coco_path /path/to/coco
```

The code I used to evaluate my model
```python
ckpt_path = 'checkpoint.pth'
python detr/main.py \
  --num_classes=2 \
  --batch_size=2 \
  --no_aux_loss \
  --eval \
  --resume $my_ckpt_path \
  --coco_path='datasets'
```

My dataset folder structure which is in coco format
```
datasets
   --- train_imgs
   --- train.json
   --- val_imgs
   --- val.json
```

My checkpoint folder structure 
```
eval
  |-- 000.pth
  |-- latest.pth
checkpoint.pth
log.txt
```

Desirable output
```bash
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.420
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.624
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.442
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.205
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.458
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.611
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.333
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.533
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.574
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.312
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.628
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.805
```
I saw this [similar issue](https://github.com/facebookresearch/detr/issues/221#issue-692580759) but it was closed without explanation. Thanks!

**Comment by lhk1234** [comment]
Hi! Have you got solution for this!?
Thanks a lot

**Comment by NyanAung436** [comment]
@lhk1234  I couldn't fix but the coco metrics evaluation shows while training

**Comment by lhk1234** [comment]
@NyanAung436 ye, I got it, too.
Thanks
