### ISSUE TITLE
HTTP Error in Downloading Models

### ISSUE THREAD

**Issue by anantgupta129** [facebookresearch/detr#433]
While downloading the model using torch hub i am facing HTTP Error 403 in google colab and in kaggle aslo if i try it on my local system its giving me HTTP Error 404.
```
model, postprocessor = torch.hub.load(
    'facebookresearch/detr', 'detr_resnet101_panoptic', pretrained=True, return_postprocessor=True, num_classes=250
)
```

```
Traceback (most recent call last):
  File "autolabellingstuff.py", line 44, in <module>
    'facebookresearch/detr', 'detr_resnet101_panoptic', pretrained=True, return_postprocessor=True, num_classes=250
  File "/usr/local/lib/python3.7/dist-packages/torch/hub.py", line 362, in load
    repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose)
  File "/usr/local/lib/python3.7/dist-packages/torch/hub.py", line 162, in _get_cache_or_reload
    _validate_not_a_forked_repo(repo_owner, repo_name, branch)
  File "/usr/local/lib/python3.7/dist-packages/torch/hub.py", line 124, in _validate_not_a_forked_repo
    with urlopen(url) as r:
  File "/usr/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: rate limit exceeded
```

**Comment by VinceKumar** [comment]
Yup I get this issue too

**Comment by anantgupta129** [comment]
> Yup I get this issue too

Did you solve it?

**Comment by Martynas99** [comment]
It seems to be pytorch issue:
https://github.com/pytorch/vision/issues/4156

**Comment by anantgupta129** [comment]
> It seems to be pytorch issue:
> [pytorch/vision#4156](https://github.com/pytorch/vision/issues/4156)

But it says to download from torchvision and i couldn't find DeTr in torchvision

**Comment by Martynas99** [comment]
You could try using this:
https://github.com/pytorch/vision/issues/4156#issuecomment-894768539
