### ISSUE TITLE
docker envirment missing something

### ISSUE THREAD

**Issue by johngrabner** [facebookresearch/detr#98]
## Instructions To Reproduce the 🐛 Bug:

1. what changes you made (`git diff`) or what code you wrote
```
no changes.
```
2. what exact command you run:
2.0 download and expand cocoa dataset into /home/john/Documents/coco as specified in README.md
2.1 download zip from github
2.2 expand into /Documents/detr-master
2.3 docker
2.3.1  docker build -t detr .
2.3.2  sudo docker run --gpus all -it --rm -v /home/john/Documents:/home/john/Documents  detr
2.4 inside docker sh
2.4.1 cd /home/john/Documents/detr-master
2.4.2 python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py --coco_path /home/john/Documents/coco

3. what you observed (including __full logs__):
```
root@374f95afa6a5:/home/john/Documents/detr-master# python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py --coco_path /home/john/Documents/coco
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
| distributed init (rank 0): env://
Traceback (most recent call last):
  File "main.py", line 248, in <module>
    main(args)
  File "main.py", line 106, in main
    utils.init_distributed_mode(args)
  File "/home/john/Documents/detr-master/util/misc.py", line 390, in init_distributed_mode
    world_size=args.world_size, rank=args.rank)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 393, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 172, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/cuda/Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "main.py", line 248, in <module>
    main(args)
  File "main.py", line 106, in main
    utils.init_distributed_mode(args)
  File "/home/john/Documents/detr-master/util/misc.py", line 385, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py", line 245, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/cuda/Module.cpp:59
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/cuda/Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "main.py", line 248, in <module>
    main(args)
  File "main.py", line 106, in main
    utils.init_distributed_mode(args)
  File "/home/john/Documents/detr-master/util/misc.py", line 385, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py", line 245, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/cuda/Module.cpp:59
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/cuda/Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "main.py", line 248, in <module>
    main(args)
  File "main.py", line 106, in main
    utils.init_distributed_mode(args)
  File "/home/john/Documents/detr-master/util/misc.py", line 385, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py", line 245, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/cuda/Module.cpp:59
| distributed init (rank 1): env://
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/cuda/Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "main.py", line 248, in <module>
    main(args)
  File "main.py", line 106, in main
    utils.init_distributed_mode(args)
  File "/home/john/Documents/detr-master/util/misc.py", line 385, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py", line 245, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/cuda/Module.cpp:59
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/cuda/Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "main.py", line 248, in <module>
    main(args)
  File "main.py", line 106, in main
    utils.init_distributed_mode(args)
  File "/home/john/Documents/detr-master/util/misc.py", line 385, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py", line 245, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/cuda/Module.cpp:59
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/cuda/Module.cpp line=59 error=101 : invalid device ordinal
Traceback (most recent call last):
  File "main.py", line 248, in <module>
    main(args)
  File "main.py", line 106, in main
    utils.init_distributed_mode(args)
  File "/home/john/Documents/detr-master/util/misc.py", line 385, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/opt/conda/lib/python3.7/site-packages/torch/cuda/__init__.py", line 245, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: cuda runtime error (101) : invalid device ordinal at /opt/conda/conda-bld/pytorch_1587428398394/work/torch/csrc/cuda/Module.cpp:59
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', '-u', 'main.py', '--coco_path', '/home/john/Documents/coco']' returned non-zero exit status 1.

```
4. please simplify the steps as much as possible so they do not require additional resources to
	 run, such as a private dataset.

## Expected behavior:

wanted to train a few epochs to verify installation before changing training set.

## Environment:

Provide your environment information using the following command:
```
python -m torch.utils.collect_env
```
root@374f95afa6a5:/home/john/Documents/detr-master# python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN RTX
GPU 1: TITAN RTX

Nvidia driver version: 440.44
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.5.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.6.1                    pypi_0    pypi
root@374f95afa6a5:/home/john/Documents/detr-master#

**Comment by johngrabner** [comment]
forgot to include, pc with 2 gpu, from the sh inside the docker
>>> torch.cuda.is_available()
True
>>> torch.cuda.get_device_name(0)
'TITAN RTX'
>>> torch.cuda.get_device_name(1)
'TITAN RTX'

**Comment by johngrabner** [comment]
Your README.ms says "To train baseline DETR on a single node with 8 gpus for 300 epochs run: ...
python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py --coco_path /path/to/coco"

May I suggest you change the run line to 
"... --nproc_per_node=NUM_GPUS_YOU_HAVE ..."

I'll close the bug, but this little change could save some time on others trying to switch from tensorflow.

**Comment by johngrabner** [comment]
Another related problem with instructions. shm needs to be greater than 172M but docker allocates only 64 by default.

```
df -h
Filesystem      Size  Used Avail Use% Mounted on
shm              64M     0   64M   0% /dev/shm

this causes the following error
index created!
Start training
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/multiprocessing/queues.py", line 236, in _feed
    obj = _ForkingPickler.dumps(obj)
```

Therefore suggest 2nd documentation change, be explicit for docker command: 
docker run --gpus all -it --rm --shm-size 256M -v /home/john/Documents:/home/john/Documents detr

**Comment by johngrabner** [comment]
256M of shared is not enough, it about and crashed after a couple of hrs.
So --shm-size 1G probably more realistic

**Comment by fmassa** [comment]
Hi,

We would gladly accept PRs improving the Dockerfile and the README, could you send it?
